"""Writes the committed sample datasets in samples/. Deterministic (fixed seeds),
so the CSVs can be regenerated byte-for-byte:  uv run samples_gen.py"""

from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).parent / "samples"


def trial() -> pd.DataFrame:
    rng = np.random.default_rng(7)
    rows = []
    for i in range(60):
        arm = ["Placebo", "Low", "High"][i // 20]
        dose = {"Placebo": 0, "Low": 10, "High": 20}[arm]
        baseline = round(float(rng.normal(50, 8)), 1)
        change = round(float(rng.normal({"Placebo": -1, "Low": -4, "High": -8}[arm], 3)), 1)
        rows.append(
            {
                "subject_id": f"S{i + 1:03d}",
                "arm": arm,
                "sex": "F" if i % 2 == 0 else "M",
                "dose": dose,
                "baseline": baseline,
                "week12": round(baseline + change, 1),
                "change": change,
                "visit_date": (pd.Timestamp("2024-01-01") + pd.Timedelta(days=i)).strftime("%Y-%m-%d"),
            }
        )
    return pd.DataFrame(rows)


def survival() -> pd.DataFrame:
    rng = np.random.default_rng(11)
    rows = []
    for i in range(80):
        arm = "Control" if i < 40 else "Treatment"
        scale = 14 if arm == "Control" else 24
        t = float(rng.exponential(scale))
        censor = float(rng.uniform(6, 36))
        rows.append(
            {
                "id": i + 1,
                "arm": arm,
                "time_months": round(min(t, censor), 1),
                "event": int(t <= censor),
                "age": int(rng.integers(45, 80)),
            }
        )
    return pd.DataFrame(rows)


def meta() -> pd.DataFrame:
    return pd.DataFrame(
        {
            "study": ["Adams 2015", "Brown 2016", "Chen 2017", "Diaz 2018", "Evans 2019", "Fox 2020", "Garcia 2021", "Hughes 2022"],
            "year": [2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022],
            "hr": [0.72, 0.85, 0.64, 0.91, 0.78, 1.05, 0.69, 0.81],
            "ci_low": [0.55, 0.66, 0.44, 0.74, 0.60, 0.82, 0.50, 0.67],
            "ci_high": [0.94, 1.09, 0.93, 1.12, 1.01, 1.34, 0.95, 0.98],
            "weight": [12.1, 15.4, 8.2, 18.9, 11.7, 9.8, 10.3, 13.6],
        }
    )


if __name__ == "__main__":
    HERE.mkdir(exist_ok=True)
    for name, frame in {"trial": trial(), "survival": survival(), "meta": meta()}.items():
        frame.to_csv(HERE / f"{name}.csv", index=False)
        print(f"wrote samples/{name}.csv ({len(frame)} rows)")
