"use client";

import { useState } from "react";
import type { ReviewTier } from "@/lib/review/reviewTypes";
import { Coin } from "../account/AccountButton";

// The one place in the app where a plain-language notice and an explicit
// confirm action are non-negotiable (CLAUDE.md rule 3: "any feature that
// sends text out of the browser is opt-in, with a plain language notice
// first"). No default-on path — onConfirm only fires from a real click, and
// only after an unticked box is ticked: explicit consent, which also covers
// sensitive (health) data about the user in a manuscript (GDPR Art. 9(2)(a)).
export default function ReviewConsent({
  journalName,
  tier,
  passCount,
  excludedCount,
  price,
  balance,
  onConfirm,
  onCancel,
}: {
  journalName: string;
  tier: ReviewTier;
  passCount: number;
  excludedCount: number;
  price: number;
  balance: number;
  onConfirm: () => void;
  onCancel: () => void;
}) {
  const [agreed, setAgreed] = useState(false);
  return (
    <div className="sheet mt-5 border-l-4 border-away p-5 sm:p-6" role="alertdialog" aria-label="Review consent">
      <p className="mb-2 flex items-center gap-2 text-xs font-medium text-away">
        <span aria-hidden className="h-2 w-2 rounded-full bg-away shadow-[0_0_0_4px_rgba(161,90,63,.12)]" />
        Sends text off this device
      </p>
      <p className="font-serif text-lg font-medium">Send this paper&apos;s text to Claude for a {tier} review?</p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        Unlike matching and the structural checks, this sends your paper&apos;s text to Anthropic&apos;s Claude API, in the United States, to review it
        against {journalName}&apos;s guidelines at {tier} depth. It goes in {passCount} requests: each carries the paper&apos;s text and does one part of
        the review (a section each, the reporting checklist at thorough depth, then the final report), and Anthropic may hold the text in memory for a
        few minutes to reuse it between them. We try to remove author names and email addresses first; this is automatic and can miss some, so check.
        The paper&apos;s content itself is sent as it is. MargaLink doesn&apos;t store it; the finished review is kept only in your browser.
        Anthropic doesn&apos;t use it to train models and deletes it within 30 days; it may keep it longer only to enforce its Usage Policy or where the
        law requires. This is the one feature in MargaLink that sends your whole paper&apos;s text off your device; Rewrite sends only a passage you
        select.
        {excludedCount > 0 &&
          ` The ${excludedCount} section${excludedCount === 1 ? "" : "s"} you marked "Don't send" won't be sent at all.`}
      </p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        <strong className="font-medium text-ink">Please don&apos;t send</strong> identifiable data about study participants, patients or other people, a
        manuscript you received as a reviewer or editor, or work you don&apos;t have permission to share.
      </p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        The review is generated by AI. It can be wrong: check it before you rely on it. Your journal may ask you to disclose AI assistance.
      </p>
      <p className="mt-3 flex items-start gap-2 text-sm leading-relaxed" data-testid="review-price">
        <Coin className="mt-0.5" />
        <span>
          This review costs <strong className="font-medium">{price} M coins</strong>; you have {balance}. If part of it doesn&apos;t come back (a section, the reporting checklist or the final report), you get that part&apos;s coins back automatically, about two hours after it starts. Resuming or retrying
          within those two hours costs nothing more.
        </span>
      </p>
      {balance < price && (
        <p className="mt-2 text-sm text-away">
          You need {price - balance} more M coin{price - balance === 1 ? "" : "s"} for this review.{" "}
          <a href="/pricing#packs" target="_blank" rel="noopener" className="text-accent underline-offset-2 hover:underline">
            Buy coins
          </a>{" "}
          <span className="text-ink-soft">(opens in a new tab; your paper stays here)</span>
        </p>
      )}
      <label className="mt-4 flex items-start gap-2 text-sm leading-relaxed">
        <input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} className="mt-1 accent-[var(--accent)]" />
        <span>
          I agree to send this text to Anthropic for this review. If it contains health or other sensitive information about me, I give my explicit
          consent.
        </span>
      </label>
      <div className="mt-4 flex flex-wrap gap-3 text-sm">
        <button type="button" onClick={onConfirm} disabled={!agreed || balance < price} className="clay-btn clay-primary h-10 px-5 font-medium disabled:opacity-50">
          Send it and review ({price} M coins)
        </button>
        <button type="button" onClick={onCancel} className="clay-btn h-10 px-5">
          Cancel
        </button>
      </div>
    </div>
  );
}
