"use client";

import { useState } from "react";
import { REWRITE_MAX_WORDS, REWRITE_MAX_WORDS_EXPAND, REWRITE_WORDS_PER_COIN } from "@/lib/accounts/coins";
import { Coin } from "../account/AccountButton";

// Rewrite's notice (CLAUDE.md rule 3: anything that sends text off the
// device is opt-in, with a plain-language notice first). Its own file, like
// the review's and Ask Claude's, so a reviewer can read verbatim what a
// person was told. Given once per paper, in this browser
// (ProjectMeta.rewriteConsent, never in a backup), and only by a real click
// after an unticked box is ticked: explicit consent, which also covers
// sensitive (health) data about the person in a manuscript (GDPR Art. 9(2)(a)).
// It can be turned off again from the commands.
export default function RewriteConsent({ onConfirm, onCancel }: { onConfirm: () => void; onCancel: () => void }) {
  const [agreed, setAgreed] = useState(false);
  return (
    <div className="border-l-4 border-away pl-4" role="alertdialog" aria-label="Rewrite consent">
      <p className="mb-2 flex items-center gap-2 text-xs font-medium text-away">
        <span aria-hidden className="h-2 w-2 rounded-full bg-away shadow-[0_0_0_4px_rgba(161,90,63,.12)]" />
        Sends text off this device
      </p>
      <p className="font-serif text-lg font-medium">Turn on Rewrite for this paper?</p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        Rewrite sends only the text you select, with the tool you choose and the paper&apos;s English, to Anthropic&apos;s Claude API in the United
        States, through our server, which keeps none of it. Citations, references, equations and pictures in the selection stay here: Claude sees a
        numbered marker in their place. Anthropic doesn&apos;t use the text to train models and deletes it within 30 days; it may keep it longer only to
        enforce its Usage Policy or where the law requires.
      </p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        <strong className="font-medium text-ink">Please don&apos;t send</strong> identifiable data about study participants, patients or other people, a
        manuscript you received as a reviewer or editor, or work you don&apos;t have permission to share.
      </p>
      <p className="mt-2 text-sm leading-relaxed text-ink-soft">
        Rewrites are generated by AI. They can be wrong or shift your meaning: read each one before you replace your text. Your journal may ask you to
        disclose AI assistance.
      </p>
      <p className="mt-3 flex items-start gap-2 text-sm leading-relaxed">
        <Coin className="mt-0.5" />
        <span>
          Each rewrite costs <strong className="font-medium">1 M coin per {REWRITE_WORDS_PER_COIN} words</strong> you select (up to{" "}
          {REWRITE_MAX_WORDS.toLocaleString("en")} at a time, {REWRITE_MAX_WORDS_EXPAND.toLocaleString("en")} to expand), shown before you choose. Try again costs the same again; a rewrite that fails is
          refunded automatically.
        </span>
      </p>
      <label className="mt-4 flex items-start gap-2 text-sm leading-relaxed">
        <input type="checkbox" checked={agreed} onChange={(e) => setAgreed(e.target.checked)} className="mt-1 accent-[var(--accent)]" />
        <span>
          I agree to send the text I select in this paper to Anthropic for rewriting. If it contains health or other sensitive information about me, I
          give my explicit consent.
        </span>
      </label>
      <div className="mt-4 flex flex-wrap items-center gap-3 text-sm">
        <button type="button" onClick={onConfirm} disabled={!agreed} className="clay-btn clay-primary h-9 px-4 font-medium disabled:opacity-50">
          Turn on for this paper
        </button>
        <button type="button" onClick={onCancel} className="clay-btn h-9 px-4">
          Cancel
        </button>
      </div>
      <p className="mt-3 text-xs text-ink-soft">To turn it off again: Commands (Ctrl+K or ⌘K), &ldquo;Turn off Rewrite for this paper&rdquo;.</p>
    </div>
  );
}
